export const _ = {
  AUTO_GOAL1_SET_BY_GOALS: 'AUTO_GOAL1_SET_BY_GOALS',
  AUTO_GOAL1_SET_BY_INVS: 'AUTO_GOAL1_SET_BY_INVS',
  AUTO_GOAL1_SET_BY_PROPS: 'AUTO_GOAL1_SET_BY_PROPS',
  AUTO_INV1_BECOMES_INV2_VIA_GOAL1: 'AUTO_INV1_BECOMES_INV2_VIA_GOAL1',
  AUTO_INV1_OBTAINED_VIA_GOAL1: 'AUTO_INV1_OBTAINED_VIA_GOAL1',
  AUTO_PROP1_APPEARS_VIA_GOAL1: 'AUTO_PROP1_APPEARS_VIA_GOAL1',
  AUTO_PROP1_BECOMES_PROP2_BY_PROPS: 'AUTO_PROP1_BECOMES_PROP2_BY_PROPS',
  AUTO_PROP1_BECOMES_PROP2_VIA_GOAL1: 'AUTO_PROP1_BECOMES_PROP2_VIA_GOAL1',
  EXAMINE_PROP1_YIELDS_INV1: 'EXAMINE_PROP1_YIELDS_INV1',
  GIVE_INV1_TO_PROP1_GETS_INV2: 'GIVE_INV1_TO_PROP1_GETS_INV2',
  GOAL1_SET_BY_GIVING_INV1_TO_PROP1: 'GOAL1_SET_BY_GIVING_INV1_TO_PROP1',
  GOAL1_SET_BY_LOSING_INV1_WHEN_USED_WITH_PROP1:
    'GOAL1_SET_BY_LOSING_INV1_WHEN_USED_WITH_PROP1',
  GOAL1_SET_BY_LOSING_INV1_USED_WITH_PROP1_AND_PROPS:
    'GOAL1_SET_BY_LOSING_INV1_USED_WITH_PROP1_AND_PROPS',
  GOAL1_SET_BY_USING_INV1_WITH_INV2: 'GOAL1_SET_BY_USING_INV1_WITH_INV2',
  GOAL1_SET_BY_USING_INV1_WITH_PROP1: 'GOAL1_SET_BY_USING_INV1_WITH_PROP1',
  GOAL1_SET_BY_USING_INV1_WITH_PROP1_LOSE_PROPS:
    'GOAL1_SET_BY_USING_INV1_WITH_PROP1_LOSE_PROPS',
  GOAL1_SET_BY_USING_INV1_WITH_PROP1_NEED_GOALS:
    'GOAL1_SET_BY_USING_INV1_WITH_PROP1_NEED_GOALS',
  GOAL1_SET_BY_USING_PROP1_WITH_PROP2: 'GOAL1_SET_BY_USING_PROP1_WITH_PROP2',
  INV1_AND_INV2_COMBINE_TO_FORM_INV3: 'INV1_AND_INV2_COMBINE_TO_FORM_INV3',
  INV1_AND_INV2_GENERATE_AN_INV3: 'INV1_AND_INV2_GENERATE_AN_INV3',
  INV1_BECOMES_INV2_BY_KEEPING_INV3: 'INV1_BECOMES_INV2_BY_KEEPING_INV3',
  INV1_BECOMES_INV2_BY_KEEPING_PROP1: 'INV1_BECOMES_INV2_BY_KEEPING_PROP1',
  INV1_BECOMES_INV2_BY_LOSING_INV3: 'INV1_BECOMES_INV2_BY_LOSING_INV3',
  INV1_WITH_PROP1_REVEALS_PROP2_KEPT_ALL:
    'INV1_WITH_PROP1_REVEALS_PROP2_KEPT_ALL',
  OBTAIN_INV1_BY_INV2_WITH_PROP1_LOSE_BOTH:
    'OBTAIN_INV1_BY_INV2_WITH_PROP1_LOSE_BOTH',
  OBTAIN_INV1_BY_INV2_WITH_PROP1_LOSE_NONE:
    'OBTAIN_INV1_BY_INV2_WITH_PROP1_LOSE_NONE',
  OBTAIN_INV1_BY_LOSING_INV2_KEEPING_PROP1:
    'OBTAIN_INV1_BY_LOSING_INV2_KEEPING_PROP1',
  OBTAIN_INV1_BY_LOSING_PROP1_KEEPING_INV2:
    'OBTAIN_INV1_BY_LOSING_PROP1_KEEPING_INV2',
  OBTAIN_INV1_BY_PROP1_WITH_PROP2_LOSE_PROPS:
    'OBTAIN_INV1_BY_PROP1_WITH_PROP2_LOSE_PROPS',
  PROP1_APPEARS_WHEN_GRAB_PROP2_WITH_GOAL1:
    'PROP1_APPEARS_WHEN_GRAB_PROP2_WITH_GOAL1',
  PROP1_APPEARS_WHEN_USE_INV1_WITH_PROP2:
    'PROP1_APPEARS_WHEN_USE_INV1_WITH_PROP2',
  PROP1_BECOMES_PROP2_AS_INV1_BECOMES_INV2:
    'PROP1_BECOMES_PROP2_AS_INV1_BECOMES_INV2',
  PROP1_BECOMES_PROP2_BY_KEEPING_INV1: 'PROP1_BECOMES_PROP2_BY_KEEPING_INV1',
  PROP1_BECOMES_PROP2_BY_KEEPING_PROP3: 'PROP1_BECOMES_PROP2_BY_KEEPING_PROP3',
  PROP1_BECOMES_PROP2_BY_LOSING_INV1: 'PROP1_BECOMES_PROP2_BY_LOSING_INV1',
  PROP1_BECOMES_PROP2_BY_LOSING_PROP3: 'PROP1_BECOMES_PROP2_BY_LOSING_PROP3',
  PROP1_BECOMES_PROP2_WHEN_GRAB_INV1: 'PROP1_BECOMES_PROP2_WHEN_GRAB_INV1',
  PROP1_CHANGES_STATE_TO_PROP2_BY_KEEPING_INV1:
    'PROP1_CHANGES_STATE_TO_PROP2_BY_KEEPING_INV1',
  PROP1_GOES_WHEN_GRAB_INV1: 'PROP1_GOES_WHEN_GRAB_INV1',
  PROP1_STAYS_WHEN_GRAB_INV1: 'PROP1_STAYS_WHEN_GRAB_INV1',
  PROP1_GOES_WHEN_GRAB_INV1_WITH_GOAL1: 'PROP1_GOES_WHEN_GRAB_INV1_WITH_GOAL1',
  PROP1_STAYS_WHEN_GRAB_INV1_WITH_GOAL1:
    'PROP1_STAYS_WHEN_GRAB_INV1_WITH_GOAL1',
  TALK_TO_PROP1_GETS_INV1: 'TALK_TO_PROP1_GETS_INV1',
  TALK_TO_PROP1_WITH_GOAL1_GETS_INV1: 'TALK_TO_PROP1_WITH_GOAL1_GETS_INV1',
  THROW_INV1_AT_PROP1_GETS_INV2_LOSE_BOTH:
    'THROW_INV1_AT_PROP1_GETS_INV2_LOSE_BOTH',
  TOGGLE_PROP1_BECOMES_PROP2: 'TOGGLE_PROP1_BECOMES_PROP2',
  TOGGLE_PROP1_CHANGES_STATE_TO_PROP2: 'TOGGLE_PROP1_CHANGES_STATE_TO_PROP2',
  TOGGLE_PROP1_REVEALS_PROP2_AS_IT_BECOMES_PROP3:
    'TOGGLE_PROP1_REVEALS_PROP2_AS_IT_BECOMES_PROP3',
};
