export enum Mix {
  ErrorVerbNotIdentified,
  ErrorGrabButNoProp,
  ErrorToggleButNoInvOrProp,
  ErrorUseButNoInvOrProp,
  ErrorWithHighestValue,
  Prop,
  Inv,
  InvVsInv,
  InvVsProp,
  VerbvsProp,
  VerbvsInv,
  PropVsProp,
  AutoNeedsNothing,
}
